# Generated by Django 5.1.2 on 2024-11-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='default_name', max_length=100),
        ),
    ]
